#name: Android Tests
#
#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v3
#    - name: set up JDK 18
#      uses: actions/setup-java@v3
#      with:
#        distribution: 'temurin'
#        java-version: 18
#
#    - name: Grant execute permission for gradlew
#      run: chmod +x gradlew
#    - name: Android Test
#      run: ./gradlew testDebug
